language: ruby
rvm:
- 2.1
script:
- echo "Hello world"
notifications:
  email: false
  webhooks:
    urls:
      - $NOTIFICATION_WEBHOOK
      - $TEST_WEBHOOK
    on_success: always 
    on_failure: always 
    on_start: never   
    on_cancel: never 
    on_error: always
